scrawley/utils/models.py
from py2neo.ogm import GraphObject, Property, RelatedTo
from sqlalchemy import event
from sqlalchemy.ext.hybrid import hybrid_property

from ..extensions import db
from sqlalchemy.ext.declarative import declarative_base

from .helpers import get_current_time, slugify

# ADD TIMESTAMP TO CLASSES
class TimeStampMixin(object):
    """ Timestamping mixin
    """
    created_at = db.Column(db.DateTime, default=get_current_time())
    created_at._creation_order = 9998
    updated_at = db.Column(db.DateTime, default=get_current_time())
    updated_at._creation_order = 9998

    @staticmethod
    def _updated_at(mapper, connection, target):
        target.updated_at = get_current_time()

    @classmethod
    def __declare_last__(cls):
        event.listen(cls, 'before_update', cls._updated_at)

# ADD
class PublicResource():

    @hybrid_property
    def public_id(self):
        result = None
        value = None

        if hasattr(self, 'title'):
            value = self.title
        elif hasattr(self, 'name'):
            value = self.name
        elif hasattr(self, 'label'):
            value = self.label
        else:
            value = 'ERROR: No public ID for this resource'

        result = slugify(value)

        return result

# BASE CLASS
class Base(TimeStampMixin):

    id = db.Column(db.Integer, primary_key=True)

    @classmethod
    def save_or_update(cls, entity):

        # db.session.begin()
        try:
            transaction = db.create_transaction()
            if not transaction:
                return False

            db.session.add(transaction)
            db.session.add(entity)
            return True
        except Exception:
            db.session.rollback()
            return False
        finally:
            db.session.close()

BaseModel = declarative_base(cls=Base)

# GRAPH MODELS
class Theme_Graph(GraphObject):
    __primarykey__ = "db_id"

    db_id = Property()
    label = Property()


class Writing_Graph(GraphObject):
    __primarykey__ = "db_id"

    db_id = Property()
    title = Property()


class User_Graph(GraphObject):
    __primarykey__ = "db_id"

    db_id = Property()
    name = Property()


Writing_Graph.theme_as = RelatedTo(Theme_Graph)
Writing_Graph.owned_by = RelatedTo(User_Graph)

User_Graph.likes = RelatedTo(Theme_Graph)
User_Graph.collaborates_on = RelatedTo(Writing_Graph)

scrawley/writing/forms.py
from flask_wtf import Form
from wtforms import HiddenField, TextField, SubmitField, FileField, IntegerField, RadioField
from wtforms.validators import DataRequired


class NewWritingForm(Form):
    next = HiddenField()
    title = TextField(u'Título',
                      [DataRequired()],
                      description=u'Pense grande!')
    caption = TextField(u'Subtítulo',
                      description=u'Opcional')
    cover = FileField(u'Imagem de capa',
                      description=u'Para inspirar')
    fk_privacy = IntegerField(u'Privacidade',
                              default=2)
    privacy = RadioField(u'Privacidade',
                         [DataRequired()],
                         choices=[('1', 'Privado'), ('2', 'Público')],
                         default="('2', 'Público')")

    submit = SubmitField('Salvar')


class EditSectionForm(Form):
    next = HiddenField()
    title = TextField(u'Título da seção',
                      [DataRequired()],
                      description=u'Ex.: Capítulo 1, Introdução, etc.')
    caption = TextField(u'Subtítulo',
                      description=u'Opcional')
    text = TextField(u'Texto da seção',
                      [DataRequired()],
                      description=u'Conte a sua história')
    submit = SubmitField('Salvar')

scrawley/__init__.py
from .app import create_app

scrawley/app.py
import os
from flask import Flask
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView
from flask_login import current_user

from scrawley.auth import auth
from scrawley.home import home
from scrawley.user import User, user, Profile, Role, Privacy
from scrawley.writing import writing, Theme, Section, Writing

from .config import config_by_name
from .extensions import db, graph_db, mail, login_manager, bootstrap, editor

blueprints = [
    home,
    auth,
    user,
    writing
]

def create_app():
    app = Flask(__name__, instance_path='/tmp/scrawley/instance')
    configure_app(app)
    configure_blueprints(app, blueprints)
    configure_extensions(app)
    configure_admin(app)

    return app

def configure_app(app):
    if os.environ.get('FLASK_ENV') == 'production':
        app.config.from_object(config_by_name[os.environ.get('FLASK_ENV')])
    else:
        app.config.from_object(config_by_name['development'])

def configure_blueprints(app, blueprints):
    for blueprint in blueprints:
        app.register_blueprint(blueprint)

def configure_extensions(app):
    db.init_app(app)

    graph_db.init_app(app)

    mail.init_app(app)

    # flask-login
    login_manager.login_view = 'auth.login'

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(id)
    login_manager.init_app(app)

    bootstrap.init_app(app)
    # Forces the use of JQuery 3 instead of 2
    from flask_bootstrap import WebCDN
    app.extensions['bootstrap']['cdns']['jquery'] = WebCDN(
        '//code.jquery.com/'
    )

    editor.init_app(app)

def configure_admin(app):
    class UserView(ModelView):
        column_hide_backrefs = False
        column_list = ['id', 'active', 'email', 'name', 'public_id', 'activaction_key', 'created_at', 'updated_at', 'user', 'roles', 'likes']
        form_excluded_columns = ['password']

        def is_accessible(self):
            is_admin = User.query.filter_by(id=current_user.id).first().is_admin()
            return current_user.is_authenticated and is_admin

    class ProfileView(ModelView):
        def is_accessible(self):
            is_admin = User.query.filter_by(id=current_user.id).first().is_admin()
            return current_user.is_authenticated and is_admin

    class RoleView(ModelView):
        def is_accessible(self):
            is_admin = User.query.filter_by(id=current_user.id).first().is_admin()
            return current_user.is_authenticated and is_admin

    class PrivacyView(ModelView):
        def is_accessible(self):
            is_admin = User.query.filter_by(id=current_user.id).first().is_admin()
            return current_user.is_authenticated and is_admin

    class WritingView(ModelView):
        column_hide_backrefs = False

        def is_accessible(self):
            is_admin = User.query.filter_by(id=current_user.id).first().is_admin()
            return current_user.is_authenticated and is_admin

    class SectionView(ModelView):
        column_hide_backrefs = False
        column_list = ['fk_writing', 'title', 'caption', 'image', 'order']
        column_sortable_list = ['fk_writing', 'title', 'caption', 'image', 'order']
        column_filters = ['fk_writing', 'title', 'caption', 'image', 'order']

        def is_accessible(self):
            is_admin = User.query.filter_by(id=current_user.id).first().is_admin()
            return current_user.is_authenticated and is_admin

    class ThemeView(ModelView):
        def is_accessible(self):
            is_admin = User.query.filter_by(id=current_user.id).first().is_admin()
            return current_user.is_authenticated and is_admin

    admin = Admin(app)
    admin.add_view(UserView(User, db.session, endpoint='users'))
    admin.add_view(ProfileView(Profile, db.session, endpoint='profiles'))
    admin.add_view(RoleView(Role, db.session, endpoint='roles'))
    admin.add_view(PrivacyView(Privacy, db.session, endpoint='privacies'))
    admin.add_view(WritingView(Writing, db.session, endpoint='writings'))
    admin.add_view(SectionView(Section, db.session, endpoint='sections'))
    admin.add_view(ThemeView(Theme, db.session, endpoint='themes'))

scrawley/home/__init__.py
from .views import home

scrawley/home/views.py
from flask import Blueprint, render_template, url_for
from flask_login import current_user, login_required
from werkzeug.utils import redirect

home = Blueprint('home', __name__, url_prefix='/', template_folder='home')


@home.route('/')
def index():
    if current_user.is_authenticated:
        return redirect('feed')
    return render_template('home/index.html')


@home.route('/feed')
@home.route('/me')
@home.route('/user')
@login_required
def feed():
    return redirect(url_for('user.me'))


@home.route('/help')
def help():
    return render_template('home/help.html')

scrawley/user/__init__.py
from .models import User, Profile, Role, Privacy
from .views import user

scrawley/user/views.py
from flask import Blueprint, render_template, url_for
from flask_login import login_required, current_user
from werkzeug.utils import redirect

from scrawley.user import User, Profile
from scrawley.writing import Writing

user = Blueprint('user', __name__, url_prefix='/user')


@user.route('/<user_id>')
@login_required
def index(user_id):
    writings = Writing.query.filter_by(fk_owner=user_id).all()
    user = User.query.get(user_id)
    return render_template('user/index.html', user=user, items=writings)

@user.route('/')
@login_required
def me():
    return redirect(url_for('user.index', user_id=current_user.id))

@user.route('/profile')
@user.route('/profile/<user_id>')
@login_required
def profile(user_id=None):
    if user_id:
        user = User.query.get(user_id)
    else:
        user = current_user

    return render_template('user/profile.html', user=user)


@user.route('/settings')
@login_required
def settings():
    return render_template('user/settings.html')

scrawley/utils/__init__.py
from .models import BaseModel
from .helpers import *

scrawley/writing/__init__.py
from .models import Writing, Section, Theme
from .views import writing

scrawley/writing/views.py
from flask import render_template, Blueprint, url_for, request, flash, json
from flask_login import login_required, current_user
from werkzeug.utils import redirect, secure_filename

from scrawley.extensions import db
from scrawley.writing import Writing
from scrawley.writing.forms import EditSectionForm, NewWritingForm
from scrawley.writing.models import Section, Theme

writing = Blueprint('writing', __name__, url_prefix='/writing')

def EXAMPLE_SECTION(id, title, order):
    example = Section(
        writing_id=id,
        title=title,
        caption='Lero lero lero',
        text="""Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent consectetur enim massa, eu suscipit ipsum'
        lacinia maximus. Donec mattis pretium cursus. Cras enim ante, gravida id volutpat eu, dictum dignissim magna.
        Aenean volutpat ut libero vitae lacinia. Vestibulum ut ipsum rutrum, sollicitudin mi vestibulum, lobortis sapien.
        Curabitur ullamcorper risus sed urna dictum, a ullamcorper ipsum consequat. Cras venenatis tellus vel tristique mattis.
        Donec facilisis fermentum bibendum. Vivamus pellentesque diam quis augue suscipit gravida. Fusce pretium nunc turpis,
        vitae vestibulum lectus porttitor id. Donec posuere vehicula quam, et auctor tellus vestibulum non. Sed dapibus
        neque sem, at euismod massa tempor sed. Donec quis risus eget orci dignissim pharetra. Praesent non turpis porta,
        onsequat enim facilisis, ultricies neque.
        Quisque dictum bibendum volutpat. Integer aliquet magna vitae sagittis maximus.
        Donec porttitor ante ac massa suscipit, a varius sapien maximus.
        Vestibulum non commodo mi. Pellentesque venenatis risus vitae libero mattis porttitor.
        Donec elit tellus, molestie et iaculis vel, vulputate eget erat. Nam interdum lectus at sapien eleifend efficitur.
        Morbi vitae elementum dui, ac tincidunt justo. Mauris ut odio lectus. Nam pulvinar rhoncus leo sit amet finibus.
        Quisque consequat enim at ante consectetur, sit amet placerat est vehicula. Curabitur enim elit, commodo vel arcu
        in, consequat tempus nunc. Donec tristique sed urna volutpat lacinia.""",
        image='http://placehold.it/50x50x',
        order=order
    )
    return example

@writing.route('/')
@login_required
def index():
    writings = Writing.query.filter_by(fk_owner=current_user.id).all()
    return render_template('writing/index.html', items=writings)


@writing.route('/new', methods=['GET', 'POST'])
@login_required
def new():
    writing_item = Writing()
    form = NewWritingForm(next=request.args.get('next'), obj=writing_item)

    if request.method == 'POST':
        if form.validate_on_submit():
            form.populate_obj(writing_item)
            section = Section()
            section.title = 'I',
            section.collaborators.append(current_user)
            section.order = 1
            section.text = 'Pronto para iniciar?'
            writing_item.sections.append(section)
            writing_item.fk_owner = current_user.id
            writing_item.fk_privacy = form.privacy.data[0]

            db.session.add(writing_item)
            db.session.commit()
            flash('Seção atualizada com sucesso!')
            return render_template('writing/detail.html', writing=writing_item)

        else:
            flash('Houve algum problema para atualizar a seção!')

    return render_template('writing/new.html', form=form)


@writing.route('/<writing_id>/remove')
@login_required
def remove(writing_id):
    writing_item = Writing.query.get(writing_id)
    db.session.delete(writing_item)
    db.session.commit()

    return redirect(url_for('writing.index'))


@writing.route('/<writing_id>/')
@login_required
def detail(writing_id):
    writing_item = Writing.query.filter_by(id=writing_id).first()
    db.session.commit()

    return render_template('writing/detail.html', writing=writing_item)


@writing.route('/<writing_id>/edit')
@login_required
def edit(writing_id):
    writing_item = Writing.query.filter_by(id=writing_id).first()
    db.session.commit()

    return render_template('writing/edit.html', writing_item=writing_item)

# SECTION
@writing.route('/<writing_id>/<section_id>')
@login_required
def section_detail(writing_id, section_id):
    writing_item = Writing.query.filter_by(id=writing_id).first()
    section = [x for x in writing_item.sections if x.id == int(section_id)][0]
    db.session.commit()

    return render_template('writing/section-detail.html', writing=writing_item, section=section)


@writing.route('/<writing_id>/section/new', methods=['GET'])
@login_required
def section_new(writing_id):
    writing_item = Writing.query.filter_by(id=writing_id).first()
    section = Section()
    section.title = 'I'
    section.caption = ''
    section.collaborators.append(current_user)
    section.order = len(writing_item.sections) + 1
    section.text = 'Pronto para iniciar?'
    writing_item.sections.append(section)
    db.session.add(writing_item)
    db.session.commit()

    return redirect(url_for('writing.section_detail', writing_id=writing_item.id, section_id=section.id))


@writing.route('/<writing_id>/<section_id>/remove')
@login_required
def section_remove(writing_id, section_id):
    writing_item = Writing.query.get(writing_id)
    section = [x for x in writing_item.sections if x.id == int(section_id)][0]
    db.session.delete(section)
    db.session.commit()

    return redirect(url_for('writing.detail', writing_id=writing_item.id))


@writing.route('/<writing_id>/<section_id>/sync', methods=['POST'])
@login_required
def section_sync(writing_id, section_id):
    section = Section.query.filter_by(id=section_id).first()

    updated_text = json.loads(request.data)['text']

    section.text = updated_text
    db.session.add(section)
    db.session.commit()

    return 'Ok'


@writing.route('/<writing_id>/<section_id>/edit', methods=['GET', 'POST'])
@login_required
def section_edit(writing_id, section_id):

    writing_item = Writing.query.filter_by(id=writing_id).first()
    section = [x for x in writing_item.sections if x.id == int(section_id)][0]

    form = EditSectionForm(next=request.args.get('next'), obj=section)

    if request.method == 'POST':
        if form.validate_on_submit():
            form.populate_obj(section)
            # section.title = form.title.data
            # section.caption = form.caption.data
            # section.text = form.text.data

            db.session.add(writing_item)
            db.session.commit()
            flash('Seção atualizada com sucesso!')
            return render_template('writing/section-detail.html', form=form, writing=writing_item, section=section)

        else:
            flash('Houve algum problema para atualizar a seção!')

    return render_template('writing/section-edit.html', form=form, writing=writing_item, section=section)

# THEME
@writing.route('/theme/<theme_id>')
@login_required
def theme(theme_id):
    theme = Theme.query.get(theme_id)
    writings = Writing.query.filter(Writing.themes.any(id=theme_id)).all()
    return render_template('writing/theme.html', theme=theme, items=writings)

scrawley/templates/layouts/base.html
{% extends "bootstrap/base.html" %}

{% block head %}
    {{ super() }}
    {% block title %}
        <!-- Rede colaborativa -->
    {% endblock %}

    {% block styles -%}
        {{super()}}
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
        <link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">
    {% endblock styles %}
{% endblock %}

{% block navbar %}
	{{ super() }}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('home.index') }}"> Scrawley_ </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

            {% if current_user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('writing.index') }}"> Meus textos </a></li>

                </ul>

                <form class="navbar-form navbar-left">
                    <div class="input-group">
                      <input type="text" class="form-control" placeholder="Buscar por... bem, qualquer coisa." size="40">
                      <a class="input-group-addon btn">
                          <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                      </a>
                    </div>
                </form>
            {% endif %}


            <ul class="nav navbar-nav navbar-right">
                <li><a href="{{ url_for('home.help') }}">Quer ajuda?</a></li>

                {% if not current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.login') }}"> Entrar </a></li>
                {% endif %}

                {% if current_user.is_authenticated %}
                {% if current_user.is_admin() %}
                    <li><a href="{{ url_for('admin.index') }}"> Admin </a></li>
                {% endif %}

                <li>
                    <a href="#">
                         <span class="glyphicon glyphicon-bell" aria-hidden="true"></span>
                        Notificações <span class="badge">4</span> </a>
                </li>


                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Olá, {{ current_user.name }}!<span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu">

                        <li><a href="{{ url_for('user.index', user_id=current_user.id) }}"> Feed </a></li>

                        <li role="separator" class="divider"></li>

                        <li><a href="{{ url_for('user.profile') }}"> Perfil </a></li>
                        <li><a href="{{ url_for('user.settings') }}"> Configurações </a></li>

                        <li role="separator" class="divider"></li>

                        <li><a href="{{ url_for('auth.logout') }}"> Sair </a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>

            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
{% endblock %}


{% block content %}
    {% block flash_message %}
        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
            <div class="container">
                <div id='flash_message_container'>
                    {% for category, msg in messages %}
                        <div class="alert alert-{{ category }}">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            {{ msg }}
                        </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
        {% endwith %}
    {% endblock %}

    {% block footer %}
        <footer> 2016 Awesome, Inc.</footer>
    {% endblock %}
{% endblock %}